version: "3.7"

services:
  proxy:
    build: .
    image: thematerr/caching-proxy
    environment:
      UPSTREAM: http://example.com
      MAX_SIZE: 500m
      ALLOWED_ORIGIN: https://example.com
    ports:
      - 8080:80/tcp
